idf_component_register(
    SRCS
        "main.c"
        "thread_init.c"
        "commissioner.c"
        "uart_rx.c"
        "security.c"
        "joiner_manager.c"
        "joiner_role.c"
        "config_sync.c"
        "ota_uart.c"
        "udp_listener.c"
        "led.c"
    INCLUDE_DIRS "."
    REQUIRES
        openthread
        esp_netif
        esp_event
        nvs_flash
        driver
        esp_timer
        mbedtls
        app_update
)
